INSERT INTO tb_category(name, create_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletronics', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Moda', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Beleza', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Casa e Decoração', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Livros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Esportes', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Automotivo', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Brinquedos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Alimentos e Bebidas', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Saúde e Bem-Estar', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletrônicos de Consumo', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Móveis', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Jogos e Videogames', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Acessórios de Moda', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Tecnologia', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Jardinagem', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Música', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Animais de Estimação', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Fitness', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Ferramentas', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Arte e Artesanato', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Roupas Infantis', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletrônicos Domésticos', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Viagens e Lazer', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Joias', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Telefonia', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Culinária e Cozinha', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Filmes e Entretenimento', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Bebês e Maternidade', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Fotografia', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Calçados', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Suplementos Alimentares', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Eletrônicos de Entretenimento', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Acessórios para Carros', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Acampamento e Aventura', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Instrumentos Musicais', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Cuidados Pessoais', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Arte Digital', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Produtos Sustentáveis', NOW());
INSERT INTO tb_category(name, create_At) VALUES ('Vestuário Esportivo', NOW());
